settings:
    metrics:
        enabled: true
    storage:
        type: "flatfile"
        options:
            preload:
                type: true
                pet: true
                locale: true
                misc: true
            flatfile:
                files:
                    pet: "pets.yml"
                    type: "pet_types.yml"
                    misc: "misc.yml"
            mysql:
                prefix: "fp_"
                server: "localhost"
                port: 3306
                database: "minecraft"
                username: "minecraft"
                password: "password"
                max_pools: 8
    pet:
        spawn_on_join: true
        higher_pet: false
        categories:
            enabled: false
            types:
                default:
                    name: "Pets"
                    item: GOLD_INGOT
                combat:
                    name: "Combat"
                    item: PLAYER_HEAD
                    texture: "http://textures.minecraft.net/texture/5dcea1c34174718af2c0ee003ebeaf08840721ccda01e3e6d40d303ff86d93e1"
                farming:
                    name: "Farming"
                    item: PLAYER_HEAD
                    texture: "http://textures.minecraft.net/texture/5dcea1c34174718af2c0ee003ebeaf08840721ccda01e3e6d40d303ff86d93e1"
        multiple_pets:
            enabled: false
            limits:
                default: 2
                vip: 4
                mvp: 8
        skills:
            enabled: true
            type_specific: false
            types:
                max_health:
                    enabled: true
                    display: RED_DYE
                    levels:
                        1:
                            value: 20.0
                            cost: 500
                        2:
                            value: 25.0
                            cost: 1000
                        3:
                            value: 30.0
                            cost: 1500
                        4:
                            value: 35.0
                            cost: 5000
                        5:
                            value: 40.0
                            cost: 12500
                attack_damage:
                    enabled: true
                    display: IRON_SWORD
                    levels:
                        1:
                            value: 4
                            cost: 200
                        2:
                            value: 6.5
                            cost: 200
                        3:
                            value: 8
                            cost: 1000
                        4:
                            value: 10
                            cost: 5000
                        5:
                            value: 12.5
                            cost: 10000
                beacon:
                    enabled: true
                    display: BEACON
                    levels:
                        1:
                            value:
                                - "JUMP:1"
                            cost: 10000
                        2:
                            value:
                                - "JUMP:1"
                                - "SPEED:1"
                            cost: 20000
                        3:
                            value:
                                - "JUMP:1"
                                - "SPEED:1"
                                - "REGENERATION:1"
                            cost: 40000
                        4:
                            value:
                                - "JUMP:1"
                                - "SPEED:1"
                                - "REGENERATION:1"
                                - "INCREASE_DAMAGE:1"
                            cost: 60000
                storage:
                    enabled: true
                    display: CHEST
                    levels:
                        1:
                            value: 1
                            cost: 500
                        2:
                            value: 2
                            cost: 2000
                        3:
                            value: 4
                            cost: 5000
                        4:
                            value: 5
                            cost: 7500
                        5:
                            value: 6
                            cost: 15000
            default:
                health: 15
                max_health: 15
                attack_damage: 4
                attack_speed: 2
                movement_speed: 1
        shop:
            enabled: false
            options:
                format:
                    text: "&6[Price: %price% %currency_symbol%]"
                    currency_symbol: "$"
                    free: "&a[Free]"
                    decimal: "#"
        cooldown:
            select:
                enabled: false
                limits:
                    default: 120
                    vip: 60
                    mvp: 10
        name:
            format: "%name% &c(%health% HP)"
            default_name: "%owner%'s %type% pet"
            custom:
                enabled: true
                colors: true
                min_length: 1
                max_length: 16
        particle:
            enabled: true
            allow_customization: true
            display:
                default: REDSTONE
                barrier: BARRIER
                crit: DIAMOND_SWORD
            filter:
                enabled: "none"
                exclude:
                    - "DRAGON_BREATH"
                    - "COMPOSTER"
                include:
                    - "NOTE"
            speeds:
                slow: 35
                normal: 20
                fast: 15
                fastest: 10
        hat:
            vanilla:
                in_air:
                    enabled: true
                    distance: 20
                swimming:
                    enabled: false
            cosmetic:
                enabled: true
        light:
            cosmetic:
                enabled: false
        health:
            enabled: true
            options:
                default_health: 20.0
                max_health: 20.0
                healing:
                    enabled: true
                death_message: true
                remove_on_death: true
                damage:
                    fall: true
                    void: false
                    attack:
                        enabled: true
                        options:
                            player_attack: true
                            owner_attack: false
        teleportation:
            distance:
                enabled: true
                distance: 20.0
            call:
                enabled: true
        riding:
            enabled: false
            options:
                player_rotation: true
                allow_fly: true
    world_filter:
        enabled: false
        excluded:
            - "Spawn"
        respawn: true